apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-world.name" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}