kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: {{ .Values.role.name }}
   namespace: {{ .Values.namespace }}
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "list", "watch"]