kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: {{ .Values.role.binding.name }}
   namespace: {{ .Values.namespace }}
subjects:
 - kind: ServiceAccount
   name: {{ include "hello-world.name" . }}
   namespace: {{ .Values.namespace }}
roleRef:
   kind: Role
   name: {{ .Values.role.name }}
   apiGroup: rbac.authorization.k8s.io